check_ubu1804_task:
  container:
    dockerfile: tooling/cirrus/ubu1804/Dockerfile
  test_script:
    - cc --version
    - mkdir btmp; cd btmp; cmake -G Ninja .. && ninja && ctest -V
  always:
    junit_artifacts:
      path: "tooling/*/junit-results.xml"
      type: text/xml
      format: junit

check_ubu2004_task:
  container:
    dockerfile: tooling/cirrus/ubu2004/Dockerfile
  test_script:
    - cc --version
    - mkdir btmp; cd btmp; cmake -G Ninja .. && ninja && ctest -V
  always:
    junit_artifacts:
      path: "tooling/*/junit-results.xml"
      type: text/xml
      format: junit

check_mac_task:
  osx_instance:
    image: catalina-xcode
  install_script:
    - brew install meson
  test_script:
    - cc --version
    - mkdir btmp; cd btmp; cmake -G Xcode .. && cmake --build . && ctest -V
  always:
    junit_artifacts:
      path: "tooling/*/junit-results.xml"
      type: text/xml
      format: junit

check_bsd_task:
  freebsd_instance:
    image_family: freebsd-12-1
  install_script:
    - pkg install -y gcc cmake ninja
  test_script:
    - cc --version
    - mkdir btmp; cd btmp; cmake -G Ninja .. && ninja && ctest -V
  always:
    junit_artifacts:
      path: "tooling/*/junit-results.xml"
      type: text/xml
      format: junit
