check_task:
  container:
    dockerfile: tooling/cirrus/ubu1804/Dockerfile
  test_script:
    - mkdir btmp; cd btmp; cmake -G Ninja .. && ninja && ctest -V
  always:
    junit_artifacts:
      path: "tooling/*/junit-results.xml"
      type: text/xml
      format: junit
