language: c
os: linux
dist: bionic
sudo: required

arch:
  - ppc64le
  - s390x

before_install:
  - sudo apt-get update
  - sudo apt-get install -y ninja-build
script:
  - tail /proc/cpuinfo
  - mkdir btmp; cd btmp; cmake -G Ninja .. && ninja && ctest -V
