version: 1.2.11.1.{build}

pull_requests:
  do_not_increment_build_number: true

shallow_clone: true

image:
  - Visual Studio 2019

before_build:
  - cmd: cmake -DJUNIT=ON .

build:
  project: "zlib.sln"

platform:
  - x64
configuration:
  - Debug
  - Release

test_script:
  - ps: |
      &"ctest" -V
      $testError = $LastExitCode
      $wc = New-Object 'System.Net.WebClient'
      $jurl = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $wc.UploadFile($jurl, (Resolve-Path "$($env:APPVEYOR_BUILD_FOLDER)\example-junit.xml"))
      if ($testError -ne 0)
      {
        throw $testError
      }
